# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginRecovery(object):
    def setupUi(self, LoginRecovery):
        LoginRecovery.setObjectName("LoginRecovery")
        LoginRecovery.resize(400, 900)
        LoginRecovery.setMaximumSize(QtCore.QSize(400, 900))
        LoginRecovery.setStyleSheet("* {\n"
"    font: 75 11pt \"Arial\";\n"
"}\n"
"QLabel#appName {\n"
"    font: 75 36pt \"Arial\";\n"
"}\n"
"QLabel#RAppName {\n"
"    font: 75 36pt \"Arial\";\n"
"}\n"
"QLabel#versionName {\n"
"    padding: 0px 0px 20px;\n"
"}\n"
"QLineEdit {\n"
"    padding: 4px;\n"
"    border: 2px solid rgb(120, 120, 120);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(57, 136, 255);\n"
"}\n"
"QCheckBox {\n"
"    padding: 10px 0px 10px;\n"
"}\n"
"QPushButton#loginBtn2 {\n"
"    margin: 10px 60px 0px;\n"
"    padding: 10px 0px 10px;\n"
"}\n"
"QPushButton#nextBtn {\n"
"    margin: 10px 60px 0px;\n"
"    padding: 10px 0px 10px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginRecovery)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LRWidget = QtWidgets.QStackedWidget(LoginRecovery)
        self.LRWidget.setMaximumSize(QtCore.QSize(400, 900))
        self.LRWidget.setLineWidth(0)
        self.LRWidget.setObjectName("LRWidget")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LoginPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayoutGroup = QtWidgets.QGroupBox(self.LoginPage)
        self.topLayoutGroup.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.topLayoutGroup.setObjectName("topLayoutGroup")
        self.topLayout = QtWidgets.QGridLayout(self.topLayoutGroup)
        self.topLayout.setContentsMargins(0, 0, 0, 0)
        self.topLayout.setSpacing(0)
        self.topLayout.setObjectName("topLayout")
        self.jargon = QtWidgets.QLabel(self.topLayoutGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jargon.sizePolicy().hasHeightForWidth())
        self.jargon.setSizePolicy(sizePolicy)
        self.jargon.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.jargon.setObjectName("jargon")
        self.topLayout.addWidget(self.jargon, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.appName = QtWidgets.QLabel(self.topLayoutGroup)
        self.appName.setStyleSheet("color: rgb(255, 255, 255);")
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName("appName")
        self.topLayout.addWidget(self.appName, 3, 1, 1, 1)
        self.versionName = QtWidgets.QLabel(self.topLayoutGroup)
        self.versionName.setStyleSheet("color: rgb(255, 255, 255);")
        self.versionName.setAlignment(QtCore.Qt.AlignCenter)
        self.versionName.setObjectName("versionName")
        self.topLayout.addWidget(self.versionName, 4, 1, 1, 1)
        self.imageLabel = QtWidgets.QLabel(self.topLayoutGroup)
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap("resources/reavaultDark.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.topLayout.addWidget(self.imageLabel, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout.addItem(spacerItem3, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.topLayoutGroup)
        self.LoginGroup = QtWidgets.QGroupBox(self.LoginPage)
        self.LoginGroup.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.LoginGroup.setObjectName("LoginGroup")
        self.bottomLayout_2 = QtWidgets.QGridLayout(self.LoginGroup)
        self.bottomLayout_2.setContentsMargins(0, 0, 0, 0)
        self.bottomLayout_2.setSpacing(0)
        self.bottomLayout_2.setObjectName("bottomLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_2.addItem(spacerItem4, 12, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_2.addItem(spacerItem5, 13, 1, 1, 1)
        self.userField_2 = QtWidgets.QLineEdit(self.LoginGroup)
        self.userField_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.userField_2.setObjectName("userField_2")
        self.bottomLayout_2.addWidget(self.userField_2, 5, 1, 1, 1)
        self.paswordLabel2 = QtWidgets.QLabel(self.LoginGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paswordLabel2.sizePolicy().hasHeightForWidth())
        self.paswordLabel2.setSizePolicy(sizePolicy)
        self.paswordLabel2.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.paswordLabel2.setObjectName("paswordLabel2")
        self.bottomLayout_2.addWidget(self.paswordLabel2, 6, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_2.addItem(spacerItem6, 12, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        self.userLabel_3 = QtWidgets.QLabel(self.LoginGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userLabel_3.sizePolicy().hasHeightForWidth())
        self.userLabel_3.setSizePolicy(sizePolicy)
        self.userLabel_3.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.userLabel_3.setObjectName("userLabel_3")
        self.bottomLayout_2.addWidget(self.userLabel_3, 4, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_2.addItem(spacerItem8, 11, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_2.addItem(spacerItem9, 8, 1, 1, 1)
        self.loginBtn2 = QtWidgets.QPushButton(self.LoginGroup)
        self.loginBtn2.setStyleSheet("QPushButton {\n"
"    background-color: #2861b6;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(47, 117, 214);\n"
"}")
        self.loginBtn2.setObjectName("loginBtn2")
        self.bottomLayout_2.addWidget(self.loginBtn2, 9, 1, 1, 1)
        self.passwordField2 = QtWidgets.QLineEdit(self.LoginGroup)
        self.passwordField2.setStyleSheet("color: rgb(255, 255, 255);")
        self.passwordField2.setObjectName("passwordField2")
        self.bottomLayout_2.addWidget(self.passwordField2, 7, 1, 1, 1)
        self.recoveryBtn2 = QtWidgets.QPushButton(self.LoginGroup)
        self.recoveryBtn2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:none;\n"
"    color:black;\n"
"    padding:0px;\n"
"    font: 9pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border:none;\n"
"    color:rgb(85, 85, 255);\n"
"}")
        self.recoveryBtn2.setObjectName("recoveryBtn2")
        self.bottomLayout_2.addWidget(self.recoveryBtn2, 12, 1, 1, 1)
        self.verticalLayout.addWidget(self.LoginGroup)
        self.LRWidget.addWidget(self.LoginPage)
        self.RecoveryPage = QtWidgets.QWidget()
        self.RecoveryPage.setObjectName("RecoveryPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.RecoveryPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LogoPlace = QtWidgets.QGroupBox(self.RecoveryPage)
        self.LogoPlace.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.LogoPlace.setObjectName("LogoPlace")
        self.topLayout_2 = QtWidgets.QGridLayout(self.LogoPlace)
        self.topLayout_2.setContentsMargins(0, 0, 0, 0)
        self.topLayout_2.setSpacing(0)
        self.topLayout_2.setObjectName("topLayout_2")
        self.label = QtWidgets.QLabel(self.LogoPlace)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 11pt \"Arial\";")
        self.label.setObjectName("label")
        self.topLayout_2.addWidget(self.label, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.LogoPlace)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 11pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.topLayout_2.addWidget(self.label_2, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_2.addItem(spacerItem10, 4, 1, 1, 1)
        self.RAppName = QtWidgets.QLabel(self.LogoPlace)
        self.RAppName.setStyleSheet("color: rgb(255, 255, 255);")
        self.RAppName.setAlignment(QtCore.Qt.AlignCenter)
        self.RAppName.setObjectName("RAppName")
        self.topLayout_2.addWidget(self.RAppName, 3, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_2.addItem(spacerItem11, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_2.addItem(spacerItem12, 1, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_2.addItem(spacerItem13, 7, 1, 1, 1)
        self.imageLabel_2 = QtWidgets.QLabel(self.LogoPlace)
        self.imageLabel_2.setText("")
        self.imageLabel_2.setPixmap(QtGui.QPixmap("resources/reavaultDark.png"))
        self.imageLabel_2.setScaledContents(True)
        self.imageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel_2.setObjectName("imageLabel_2")
        self.topLayout_2.addWidget(self.imageLabel_2, 1, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_2.addItem(spacerItem14, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.LogoPlace)
        self.RecoveryGroup = QtWidgets.QGroupBox(self.RecoveryPage)
        self.RecoveryGroup.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.RecoveryGroup.setObjectName("RecoveryGroup")
        self.bottomLayout_3 = QtWidgets.QGridLayout(self.RecoveryGroup)
        self.bottomLayout_3.setContentsMargins(0, 0, 0, 0)
        self.bottomLayout_3.setSpacing(0)
        self.bottomLayout_3.setObjectName("bottomLayout_3")
        self.answerLabel = QtWidgets.QLabel(self.RecoveryGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answerLabel.sizePolicy().hasHeightForWidth())
        self.answerLabel.setSizePolicy(sizePolicy)
        self.answerLabel.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.answerLabel.setObjectName("answerLabel")
        self.bottomLayout_3.addWidget(self.answerLabel, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem15 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_3.addItem(spacerItem15, 12, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_3.addItem(spacerItem16, 9, 1, 1, 1)
        self.questionLabel = QtWidgets.QLabel(self.RecoveryGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questionLabel.sizePolicy().hasHeightForWidth())
        self.questionLabel.setSizePolicy(sizePolicy)
        self.questionLabel.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.questionLabel.setObjectName("questionLabel")
        self.bottomLayout_3.addWidget(self.questionLabel, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_3.addItem(spacerItem17, 0, 1, 1, 1)
        self.answerField = QtWidgets.QLineEdit(self.RecoveryGroup)
        self.answerField.setStyleSheet("color: rgb(255, 255, 255);")
        self.answerField.setObjectName("answerField")
        self.bottomLayout_3.addWidget(self.answerField, 8, 1, 1, 1)
        self.nextBtn = QtWidgets.QPushButton(self.RecoveryGroup)
        self.nextBtn.setStyleSheet("QPushButton{\n"
"    background-color: #2861b6;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(47, 117, 214);\n"
"}")
        self.nextBtn.setObjectName("nextBtn")
        self.bottomLayout_3.addWidget(self.nextBtn, 10, 1, 1, 1)
        self.questionBox = QtWidgets.QComboBox(self.RecoveryGroup)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.questionBox.setFont(font)
        self.questionBox.setStyleSheet("color:rgb(255, 255, 255);")
        self.questionBox.setObjectName("questionBox")
        self.questionBox.addItem("")
        self.questionBox.addItem("")
        self.questionBox.addItem("")
        self.bottomLayout_3.addWidget(self.questionBox, 5, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_3.addItem(spacerItem18, 6, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_3.addItem(spacerItem19, 13, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_3.addItem(spacerItem20, 12, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.RecoveryGroup)
        self.LRWidget.addWidget(self.RecoveryPage)
        self.horizontalLayout.addWidget(self.LRWidget)

        self.retranslateUi(LoginRecovery)
        self.LRWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginRecovery)
        
        self.recoveryBtn2.clicked.connect(lambda: self.changePage(1))
        self.loginBtn2.clicked.connect(self.verifyLogin)

    def errorMsg(self, information="Username or Password Incorect"):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Critical)

        msg.setText(information)
        msg.setWindowTitle("Error")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.exec_()

    def verifyLogin(self):
        self.uname = self.userField_2.text()
        self.pwd = self.passwordField2.text()
        res = self.reavault.loginUser([self.uname, self.pwd])
        if res == True:
            self.App.show()
            self.Login.close()
        else:
            self.errorMsg()

    def changePage(self, index, mode=None):
        self.LoginRecovey.setCurrentIndex(index)

    def setBridge(self, reavault):
        self.reavault = reavault

    def setter(self, Login, App):
        self.Login = Login
        self.App = App

    def retranslateUi(self, LoginRecovery):
        _translate = QtCore.QCoreApplication.translate
        LoginRecovery.setWindowTitle(_translate("LoginRecovery", "Login - Reavault"))
        self.jargon.setText(_translate("LoginRecovery", "\"Password Manager No.1 se-UTM\""))
        self.appName.setText(_translate("LoginRecovery", "Reavault"))
        self.versionName.setText(_translate("LoginRecovery", "Version Beta 0.0.1"))
        self.paswordLabel2.setText(_translate("LoginRecovery", "Password"))
        self.userLabel_3.setText(_translate("LoginRecovery", "Username"))
        self.loginBtn2.setText(_translate("LoginRecovery", "Login"))
        self.recoveryBtn2.setText(_translate("LoginRecovery", "Forgot Password?"))
        self.label.setText(_translate("LoginRecovery", "Pada bagian ini, jawab sesuai dengan instruksi"))
        self.label_2.setText(_translate("LoginRecovery", "pertanyaan yang telah tersedia dengan tepat"))
        self.RAppName.setText(_translate("LoginRecovery", "Recovery"))
        self.answerLabel.setText(_translate("LoginRecovery", "ANSWER"))
        self.questionLabel.setText(_translate("LoginRecovery", "QUESTION"))
        self.answerField.setPlaceholderText(_translate("LoginRecovery", "Input your answer"))
        self.nextBtn.setText(_translate("LoginRecovery", "NEXT"))
        self.questionBox.setItemText(0, _translate("LoginRecovery", "Siapa nama panggilanmu?"))
        self.questionBox.setItemText(1, _translate("LoginRecovery", "Tanggal berapa kamu lahir?"))
        self.questionBox.setItemText(2, _translate("LoginRecovery", "Dimana alamat rumahmu?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginRecovery = QtWidgets.QWidget()
    ui = Ui_LoginRecovery()
    ui.setupUi(LoginRecovery)
    LoginRecovery.show()
    sys.exit(app.exec_())
