# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dark1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_storageDark(object):

    def setBridge(self, reavault):
        self.reavault = reavault
        self.globalTags = []
        self.globalCategories = []
        self.globalResTags = []

    def update(self, index, mode=None):
        if mode=="Create":
            self.loadCreateComponent()

        elif mode=="CreateUpload":
            self.upload()

        elif mode=="CancelUpdate":
            self.removeUpdateComponent()

        elif mode=="CancelCreate":
            self.removeCreateComponent()

    def errorMsg(self, information="Field Should Full"):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Critical)

        msg.setText(information)
        msg.setWindowTitle("Error")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.exec_()

    def upload():
        title = self.cTitle.text()
        target = self.cTargetField.text()
        desc = self.cDescription.text()
        username = self.cUsername.text()
        pwd = self.cPassword.text()

        if self.cCategoryField.text().isspace() == False or self.cCategoryField.text() != '':
            category = self.cCategoryField.text()

        tags = self.globalResTags
        color = cColorBox.currentText()
        types = cTypeBox.currentText()

        if title.isspace() == True or title == '':
            self.errorMsg()
            return
        elif target.isspace() == True or target == '':
            self.errorMsg()
            return
        elif desc.isspace() == True or desc == '':
            self.errorMsg()
            return
        elif username.isspace() == True or username == '':
            self.errorMsg()
            return
        elif password.isspace() == True or password == '':
            self.errorMsg()
            return

        self.reavault.

    def globalLoader(self):
        self.allData = self.reavault.getAllData()
        self.getId = self.allData[-1][0]
        tagsTmp = self.reavault.getAttribute("SELECT tag_name FROM tags;")
        for a in tagsTmp:
            self.globalTags.append(str(a[0]))
        catTmp = self.reavault.getAttribute("SELECT category_name FROM categories;")
        for a in catTmp:
            self.globalTags.append(str(a[0]))
            
    def loadCreateComponent(self):
        for i in self.globalTag:
            tagItem = QtWidgets.QCheckBox(self.cMainContent)
            tagItem.setText(i)
            tagItem.toogle.connect(lambda: self.tagOnClick(tagItem))
            tagItem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            tagItem.setStyleSheet("color:rgb(255, 255, 255);\n"
        "font: 11pt \"Arial\";\n"
        "")
            self.cTagContainer.addWidget(tagItem)

        self.cCategoryBox.addItems(self.globalCategories)

    def tagOnClick(self, b):
        if b.isChecked():
            self.globalResTags.append(b.text())
        else:
            try:
                self.globalResTags.remove(b.text())
            except:
                print()

    def addTag(self):
        newTag = self.cTagField.text()
        if newTag.isspace() == False or newTag != '':
            self.globalTags.append(newTag)
            self.loadCreateComponent

    def setItemSideBar(self):
        self.globalState()
        self.allData = self.reavault.getAllData()
        print(self.allData)

        for i in range(len(self.allData)):
            push = QtWidgets.QPushButton(self.vLMainBox)
            push.setText(str(self.allData[i][1]))
            font = QtGui.QFont()
            font.setFamily("Arial")
            font.setPointSize(12)
            push.setFont(font)
            push.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            push.setStyleSheet("QPushButton:hover {\n"
            "    background-color: #3A6187;\n"
            "}")
            push.clicked.connect(lambda: self.sideBarTitleOnClick(i))
            self.verticalLayout_4.addWidget(push)

    def sideBarTitleOnClick(self, index):
        for i in reversed(range(self.vTagContainer.count())): 
            self.vTagContainer.itemAt(i).widget().setParent(None)
        self.vTitle.show()
        self.vUsername.show()
        self.vPassword.show()
        self.vTarget.show()
        self.vDescription.show()
        self.vCategory.show()
        self.vTypes.show()
        self.vColor.show()
        self.vEditBtn.show()
        self.deleteBtn.show()

        get = self.allData[index]
        self.vTitle.setText(get[1])
        self.vDescription.setText(get[2])
        self.vTarget.setText(get[3])
        self.vUsername.setText(get[4])
        self.vPassword.setText(get[5])
        getCategory = self.reavault.getAttribute(f"SELECT category_name FROM categories WHERE category_id = {get[6]};")
        getTag = self.reavault.getAttribute(f"SELECT tag_name FROM tags WHERE tag_id = {get[7]};")
        getType = self.reavault.getAttribute(f"SELECT type_value FROM types WHERE type_id = {get[8]};")
        getColor = self.reavault.getAttribute(f"SELECT color_code FROM colors WHERE color_id = {get[9]};")
        self.vCategory.setText(getCategory[0][0])
        self.vTypes.setText(f"Importance Level : {str(getType[0][0])}")
        self.vColor.setText(getColor[0][0])

        for i in getTag:
            self.vTags2 = QtWidgets.QLabel(self.vRMainContent)
            font = QtGui.QFont()
            font.setFamily("Arial")
            font.setPointSize(12)
            self.vTags2.setFont(font)
            self.vTags2.setText(f"#{i[0]}")
            self.vTagContainer.addWidget(self.vTags2)

    def setupUi(self, storageDark):
        storageDark.setObjectName("storageDark")
        storageDark.resize(758, 795)
        self.horizontalLayout = QtWidgets.QHBoxLayout(storageDark)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parentWidget = QtWidgets.QStackedWidget(storageDark)
        self.parentWidget.setLineWidth(0)
        self.parentWidget.setObjectName("parentWidget")
        self.vaultV = QtWidgets.QWidget()
        self.vaultV.setObjectName("vaultV")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.vaultV)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vTopNB = QtWidgets.QHBoxLayout()
        self.vTopNB.setSpacing(0)
        self.vTopNB.setObjectName("vTopNB")
        self.vCreateBtn = QtWidgets.QPushButton(self.vaultV)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vCreateBtn.setFont(font)
        self.vCreateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vCreateBtn.setStyleSheet("QPushButton{\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"}")
        self.vCreateBtn.setObjectName("vCreateBtn")
        self.vTopNB.addWidget(self.vCreateBtn)
        self.vVaultBtn = QtWidgets.QPushButton(self.vaultV)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vVaultBtn.setFont(font)
        self.vVaultBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vVaultBtn.setStyleSheet("QPushButton{\n"
"    background-color: #34495E;\n"
"    color: #dfdfdf;\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"}")
        self.vVaultBtn.setObjectName("vVaultBtn")
        self.vTopNB.addWidget(self.vVaultBtn)
        self.vSettingBtn = QtWidgets.QPushButton(self.vaultV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vSettingBtn.sizePolicy().hasHeightForWidth())
        self.vSettingBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vSettingBtn.setFont(font)
        self.vSettingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vSettingBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"    padding: 10px 10px;\n"
"}")
        self.vSettingBtn.setObjectName("vSettingBtn")
        self.vTopNB.addWidget(self.vSettingBtn)
        self.verticalLayout.addLayout(self.vTopNB)
        self.vTopLine = QtWidgets.QFrame(self.vaultV)
        self.vTopLine.setMinimumSize(QtCore.QSize(0, 6))
        self.vTopLine.setStyleSheet("background-color: #34495E;")
        self.vTopLine.setLineWidth(0)
        self.vTopLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.vTopLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vTopLine.setObjectName("vTopLine")
        self.verticalLayout.addWidget(self.vTopLine)
        self.vMain = QtWidgets.QHBoxLayout()
        self.vMain.setContentsMargins(-1, -1, 0, -1)
        self.vMain.setSpacing(0)
        self.vMain.setObjectName("vMain")
        self.vLMain = QtWidgets.QGroupBox(self.vaultV)
        self.vLMain.setStyleSheet("QGroupBox {\n"
"    background-color: #34495E;\n"
"    border: none;\n"
"}\n"
"QLabel {\n"
"    color: #dfdfdf;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    padding: 4px;\n"
"    border: none;\n"
"}\n"
"QComboBox {\n"
"    border-radius: 5px;\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    border: none;\n"
"    padding: 4px;\n"
"}")
        self.vLMain.setObjectName("vLMain")
        self.sideBar_3 = QtWidgets.QGridLayout(self.vLMain)
        self.sideBar_3.setContentsMargins(0, 0, 0, 0)
        self.sideBar_3.setSpacing(10)
        self.sideBar_3.setObjectName("sideBar_3")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.sideBar_3.addItem(spacerItem, 6, 3, 1, 1)
        self.vLMFilterLabel = QtWidgets.QLabel(self.vLMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vLMFilterLabel.sizePolicy().hasHeightForWidth())
        self.vLMFilterLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vLMFilterLabel.setFont(font)
        self.vLMFilterLabel.setObjectName("vLMFilterLabel")
        self.sideBar_3.addWidget(self.vLMFilterLabel, 6, 1, 1, 1)
        self.vLMLine2 = QtWidgets.QFrame(self.vLMain)
        self.vLMLine2.setMinimumSize(QtCore.QSize(0, 3))
        self.vLMLine2.setStyleSheet("background-color: rgb(34, 49, 63);")
        self.vLMLine2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vLMLine2.setLineWidth(0)
        self.vLMLine2.setFrameShape(QtWidgets.QFrame.HLine)
        self.vLMLine2.setObjectName("vLMLine2")
        self.sideBar_3.addWidget(self.vLMLine2, 3, 1, 1, 2)
        self.vLMFilterBox = QtWidgets.QComboBox(self.vLMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vLMFilterBox.setFont(font)
        self.vLMFilterBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vLMFilterBox.setObjectName("vLMFilterBox")
        self.vLMFilterBox.addItem("")
        self.vLMFilterBox.addItem("")
        self.vLMFilterBox.addItem("")
        self.vLMFilterBox.addItem("")
        self.sideBar_3.addWidget(self.vLMFilterBox, 6, 2, 1, 1)
        self.vLMSearchField = QtWidgets.QLineEdit(self.vLMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vLMSearchField.setFont(font)
        self.vLMSearchField.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    background-color: #3A6187;\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border:none;\n"
"    background-color:rgb(229, 229, 229);\n"
"    color:black;\n"
"}")
        self.vLMSearchField.setObjectName("vLMSearchField")
        self.sideBar_3.addWidget(self.vLMSearchField, 2, 1, 1, 2)
        self.vLMLine1 = QtWidgets.QFrame(self.vLMain)
        self.vLMLine1.setMinimumSize(QtCore.QSize(0, 3))
        self.vLMLine1.setStyleSheet("background-color: rgb(34, 49, 63);")
        self.vLMLine1.setLineWidth(0)
        self.vLMLine1.setFrameShape(QtWidgets.QFrame.HLine)
        self.vLMLine1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vLMLine1.setObjectName("vLMLine1")
        self.sideBar_3.addWidget(self.vLMLine1, 5, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.sideBar_3.addItem(spacerItem1, 7, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.sideBar_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.vLMSearchLabel = QtWidgets.QLabel(self.vLMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vLMSearchLabel.sizePolicy().hasHeightForWidth())
        self.vLMSearchLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vLMSearchLabel.setFont(font)
        self.vLMSearchLabel.setObjectName("vLMSearchLabel")
        self.sideBar_3.addWidget(self.vLMSearchLabel, 1, 1, 1, 1)
        self.vLMSearchBox = QtWidgets.QComboBox(self.vLMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vLMSearchBox.setFont(font)
        self.vLMSearchBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vLMSearchBox.setDuplicatesEnabled(False)
        self.vLMSearchBox.setFrame(True)
        self.vLMSearchBox.setObjectName("vLMSearchBox")
        self.vLMSearchBox.addItem("")
        self.vLMSearchBox.addItem("")
        self.vLMSearchBox.addItem("")
        self.vLMSearchBox.addItem("")
        self.vLMSearchBox.addItem("")
        self.sideBar_3.addWidget(self.vLMSearchBox, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.sideBar_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.vLMainContent = QtWidgets.QScrollArea(self.vLMain)
        self.vLMainContent.setStyleSheet("QPushButton {\n"
"    background-color: rgb(34, 49, 63);\n"
"    border: none;\n"
"    padding: 10px 0px;\n"
"    color: #dfdfdf;\n"
"}")
        self.vLMainContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vLMainContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vLMainContent.setLineWidth(0)
        self.vLMainContent.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vLMainContent.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vLMainContent.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.vLMainContent.setWidgetResizable(True)
        self.vLMainContent.setObjectName("vLMainContent")
        self.vLMainBox = QtWidgets.QWidget()
        self.vLMainBox.setGeometry(QtCore.QRect(0, 0, 235, 563))
        self.vLMainBox.setStyleSheet("background-color: rgb(34, 49, 63);")
        self.vLMainBox.setObjectName("vLMainBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.vLMainBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.setItemSideBar()
        
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.vLMainContent.setWidget(self.vLMainBox)
        self.sideBar_3.addWidget(self.vLMainContent, 4, 0, 1, 4)
        self.vMain.addWidget(self.vLMain)
        self.vRMain = QtWidgets.QScrollArea(self.vaultV)
        self.vRMain.setStyleSheet("background-color: rgb(28, 40, 52);\n"
"color: #DFDFDF;")
        self.vRMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vRMain.setLineWidth(0)
        self.vRMain.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vRMain.setWidgetResizable(True)
        self.vRMain.setObjectName("vRMain")
        self.vRMainContent = QtWidgets.QWidget()
        self.vRMainContent.setGeometry(QtCore.QRect(0, 0, 500, 878))
        self.vRMainContent.setObjectName("vRMainContent")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.vRMainContent)
        self.gridLayout_4.setContentsMargins(100, 50, 100, 50)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.deleteBtn = QtWidgets.QPushButton(self.vRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteBtn.sizePolicy().hasHeightForWidth())
        self.deleteBtn.setSizePolicy(sizePolicy)
        self.deleteBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 4);\n"
"    color:  black;\n"
"    border: none;\n"
"    padding: 10px 30px;\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius5px;\n"
"\n"
"}")
        self.deleteBtn.setObjectName("deleteBtn")
        self.gridLayout_4.addWidget(self.deleteBtn, 20, 1, 1, 1)
        self.vEditBtn = QtWidgets.QPushButton(self.vRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vEditBtn.sizePolicy().hasHeightForWidth())
        self.vEditBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vEditBtn.setFont(font)
        self.vEditBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.vEditBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    padding: 10px 30px;\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius5px;\n"
"\n"
"}")
        self.vEditBtn.setObjectName("vEditBtn")
        self.gridLayout_4.addWidget(self.vEditBtn, 19, 1, 1, 1)
        self.vColor = QtWidgets.QPushButton(self.vRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vColor.sizePolicy().hasHeightForWidth())
        self.vColor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vColor.setFont(font)
        self.vColor.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius:10px;\n"
"}")
        self.vColor.setObjectName("vColor")
        self.gridLayout_4.addWidget(self.vColor, 18, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 20, 0, 1, 1)
        self.vUsername = QtWidgets.QLabel(self.vRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vUsername.setFont(font)
        self.vUsername.setObjectName("vUsername")
        self.gridLayout_4.addWidget(self.vUsername, 2, 0, 1, 2)
        self.vCategory = QtWidgets.QPushButton(self.vRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vCategory.sizePolicy().hasHeightForWidth())
        self.vCategory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vCategory.setFont(font)
        self.vCategory.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius:10px;\n"
"}")
        self.vCategory.setObjectName("vCategory")
        self.gridLayout_4.addWidget(self.vCategory, 8, 0, 1, 1)
        self.vDescription = QtWidgets.QLabel(self.vRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vDescription.sizePolicy().hasHeightForWidth())
        self.vDescription.setSizePolicy(sizePolicy)
        self.vDescription.setStyleSheet("font: 10pt \"Arial\";")
        self.vDescription.setWordWrap(True)
        self.vDescription.setObjectName("vDescription")
        self.gridLayout_4.addWidget(self.vDescription, 5, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 21, 0, 1, 1)
        self.vTypes = QtWidgets.QLabel(self.vRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vTypes.setFont(font)
        self.vTypes.setObjectName("vTypes")
        self.gridLayout_4.addWidget(self.vTypes, 15, 0, 1, 1)
        self.vPassword = QtWidgets.QLabel(self.vRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vPassword.setFont(font)
        self.vPassword.setObjectName("vPassword")
        self.gridLayout_4.addWidget(self.vPassword, 3, 0, 1, 2)
        self.vTitle = QtWidgets.QLabel(self.vRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vTitle.sizePolicy().hasHeightForWidth())
        self.vTitle.setSizePolicy(sizePolicy)
        self.vTitle.setStyleSheet("font: 75 30pt \"Arial\";")
        self.vTitle.setObjectName("vTitle")
        self.gridLayout_4.addWidget(self.vTitle, 0, 0, 1, 2)
        self.vTarget = QtWidgets.QLabel(self.vRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vTarget.sizePolicy().hasHeightForWidth())
        self.vTarget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vTarget.setFont(font)
        self.vTarget.setObjectName("vTarget")
        self.gridLayout_4.addWidget(self.vTarget, 4, 0, 1, 2)
        self.vTagContainer = QtWidgets.QVBoxLayout()
        self.vTagContainer.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.vTagContainer.setContentsMargins(0, 0, 0, 0)
        self.vTagContainer.setSpacing(20)
        self.vTagContainer.setObjectName("vTagContainer")

        self.gridLayout_4.addLayout(self.vTagContainer, 9, 0, 1, 1)
        self.vRMain.setWidget(self.vRMainContent)
        self.vMain.addWidget(self.vRMain)
        self.verticalLayout.addLayout(self.vMain)
        self.parentWidget.addWidget(self.vaultV)
        self.vaultU = QtWidgets.QWidget()
        self.vaultU.setObjectName("vaultU")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.vaultU)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.uTopNB = QtWidgets.QHBoxLayout()
        self.uTopNB.setSpacing(0)
        self.uTopNB.setObjectName("uTopNB")
        self.uCreateBtn = QtWidgets.QPushButton(self.vaultU)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uCreateBtn.setFont(font)
        self.uCreateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uCreateBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"}")
        self.uCreateBtn.setObjectName("uCreateBtn")
        self.uTopNB.addWidget(self.uCreateBtn)
        self.uVaultBtn = QtWidgets.QPushButton(self.vaultU)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uVaultBtn.setFont(font)
        self.uVaultBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uVaultBtn.setStyleSheet("QPushButton {\n"
"    background-color: #34495E;\n"
"    color: #dfdfdf;\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"}")
        self.uVaultBtn.setObjectName("uVaultBtn")
        self.uTopNB.addWidget(self.uVaultBtn)
        self.uSettingBtn = QtWidgets.QPushButton(self.vaultU)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uSettingBtn.sizePolicy().hasHeightForWidth())
        self.uSettingBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uSettingBtn.setFont(font)
        self.uSettingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uSettingBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"    padding: 10px 10px;\n"
"}")
        self.uSettingBtn.setObjectName("uSettingBtn")
        self.uTopNB.addWidget(self.uSettingBtn)
        self.verticalLayout_6.addLayout(self.uTopNB)
        self.uTopLine = QtWidgets.QFrame(self.vaultU)
        self.uTopLine.setMinimumSize(QtCore.QSize(0, 6))
        self.uTopLine.setStyleSheet("background-color: #34495E;")
        self.uTopLine.setLineWidth(0)
        self.uTopLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.uTopLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.uTopLine.setObjectName("uTopLine")
        self.verticalLayout_6.addWidget(self.uTopLine)
        self.uMain = QtWidgets.QHBoxLayout()
        self.uMain.setSpacing(0)
        self.uMain.setObjectName("uMain")
        self.uLMain = QtWidgets.QGroupBox(self.vaultU)
        self.uLMain.setStyleSheet("QGroupBox{\n"
"    background-color: #34495E;\n"
"    border: none;\n"
"}\n"
"QLabel {\n"
"    color: #dfdfdf;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    padding: 4px;\n"
"    border: none;\n"
"}\n"
"QComboBox {\n"
"    border-radius: 5px;\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    border: none;\n"
"    padding: 4px;\n"
"}")
        self.uLMain.setObjectName("uLMain")
        self.sideBar_4 = QtWidgets.QGridLayout(self.uLMain)
        self.sideBar_4.setContentsMargins(0, 0, 0, 0)
        self.sideBar_4.setSpacing(10)
        self.sideBar_4.setObjectName("sideBar_4")
        spacerItem7 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.sideBar_4.addItem(spacerItem7, 6, 3, 1, 1)
        self.uLMFilterLabel = QtWidgets.QLabel(self.uLMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uLMFilterLabel.sizePolicy().hasHeightForWidth())
        self.uLMFilterLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uLMFilterLabel.setFont(font)
        self.uLMFilterLabel.setObjectName("uLMFilterLabel")
        self.sideBar_4.addWidget(self.uLMFilterLabel, 6, 1, 1, 1)
        self.uLMLine1 = QtWidgets.QFrame(self.uLMain)
        self.uLMLine1.setMinimumSize(QtCore.QSize(0, 3))
        self.uLMLine1.setStyleSheet("background-color: rgb(34, 49, 63);")
        self.uLMLine1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.uLMLine1.setLineWidth(0)
        self.uLMLine1.setFrameShape(QtWidgets.QFrame.HLine)
        self.uLMLine1.setObjectName("uLMLine1")
        self.sideBar_4.addWidget(self.uLMLine1, 3, 1, 1, 2)
        self.uLMFilterBox = QtWidgets.QComboBox(self.uLMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uLMFilterBox.setFont(font)
        self.uLMFilterBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uLMFilterBox.setObjectName("uLMFilterBox")
        self.uLMFilterBox.addItem("")
        self.uLMFilterBox.addItem("")
        self.uLMFilterBox.addItem("")
        self.uLMFilterBox.addItem("")
        self.sideBar_4.addWidget(self.uLMFilterBox, 6, 2, 1, 1)
        self.uLMSearchField = QtWidgets.QLineEdit(self.uLMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uLMSearchField.setFont(font)
        self.uLMSearchField.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    background-color: #3A6187;\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border:none;\n"
"    background-color:rgb(229, 229, 229);\n"
"    color:black;\n"
"}")
        self.uLMSearchField.setObjectName("uLMSearchField")
        self.sideBar_4.addWidget(self.uLMSearchField, 2, 1, 1, 2)
        self.uLMLine2 = QtWidgets.QFrame(self.uLMain)
        self.uLMLine2.setMinimumSize(QtCore.QSize(0, 3))
        self.uLMLine2.setStyleSheet("background-color: rgb(34, 49, 63);")
        self.uLMLine2.setLineWidth(0)
        self.uLMLine2.setFrameShape(QtWidgets.QFrame.HLine)
        self.uLMLine2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.uLMLine2.setObjectName("uLMLine2")
        self.sideBar_4.addWidget(self.uLMLine2, 5, 1, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.sideBar_4.addItem(spacerItem8, 7, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.sideBar_4.addItem(spacerItem9, 1, 0, 1, 1)
        self.uLMSearchLabel = QtWidgets.QLabel(self.uLMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uLMSearchLabel.sizePolicy().hasHeightForWidth())
        self.uLMSearchLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uLMSearchLabel.setFont(font)
        self.uLMSearchLabel.setObjectName("uLMSearchLabel")
        self.sideBar_4.addWidget(self.uLMSearchLabel, 1, 1, 1, 1)
        self.uLMSearchBox = QtWidgets.QComboBox(self.uLMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uLMSearchBox.setFont(font)
        self.uLMSearchBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uLMSearchBox.setDuplicatesEnabled(False)
        self.uLMSearchBox.setFrame(True)
        self.uLMSearchBox.setObjectName("uLMSearchBox")
        self.uLMSearchBox.addItem("")
        self.uLMSearchBox.addItem("")
        self.uLMSearchBox.addItem("")
        self.uLMSearchBox.addItem("")
        self.uLMSearchBox.addItem("")
        self.sideBar_4.addWidget(self.uLMSearchBox, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.sideBar_4.addItem(spacerItem10, 0, 1, 1, 1)
        self.uLMainContent = QtWidgets.QScrollArea(self.uLMain)
        self.uLMainContent.setStyleSheet("QPushButton {\n"
"    background-color: rgb(34, 49, 63);\n"
"    border: none;\n"
"    padding: 10px 0px;\n"
"    color: #dfdfdf;\n"
"}")
        self.uLMainContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.uLMainContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.uLMainContent.setLineWidth(0)
        self.uLMainContent.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.uLMainContent.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.uLMainContent.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.uLMainContent.setWidgetResizable(True)
        self.uLMainContent.setObjectName("uLMainContent")
        self.uLMainBox = QtWidgets.QWidget()
        self.uLMainBox.setGeometry(QtCore.QRect(0, 0, 83, 39))
        self.uLMainBox.setStyleSheet("background-color: rgb(34, 49, 63);")
        self.uLMainBox.setObjectName("uLMainBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.uLMainBox)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.uLMBoxItem1 = QtWidgets.QPushButton(self.uLMainBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uLMBoxItem1.setFont(font)
        self.uLMBoxItem1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uLMBoxItem1.setStyleSheet("QPushButton:hover {\n"
"    background-color: #3A6187;\n"
"}")
        self.uLMBoxItem1.setObjectName("uLMBoxItem1")
        self.verticalLayout_5.addWidget(self.uLMBoxItem1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.uLMainContent.setWidget(self.uLMainBox)
        self.sideBar_4.addWidget(self.uLMainContent, 4, 0, 1, 4)
        self.uMain.addWidget(self.uLMain)
        self.uRMain = QtWidgets.QScrollArea(self.vaultU)
        self.uRMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.uRMain.setLineWidth(0)
        self.uRMain.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.uRMain.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.uRMain.setWidgetResizable(True)
        self.uRMain.setObjectName("uRMain")
        self.uRMainContent = QtWidgets.QWidget()
        self.uRMainContent.setGeometry(QtCore.QRect(0, 0, 463, 838))
        self.uRMainContent.setStyleSheet("* {\n"
"    background-color: rgb(28, 40, 52);\n"
"    color: #DFDFDF;\n"
"}\n"
"QLineEdit {\n"
"    padding: 4px;\n"
"    border: 1px solid #DFDFDF;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(0, 85, 255);\n"
"}\n"
"QPushButton {\n"
"    border: 1px solid #DFDFDF;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}")
        self.uRMainContent.setObjectName("uRMainContent")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.uRMainContent)
        self.gridLayout_5.setContentsMargins(20, 20, 20, -1)
        self.gridLayout_5.setSpacing(15)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.uCategoryContainer = QtWidgets.QHBoxLayout()
        self.uCategoryContainer.setObjectName("uCategoryContainer")
        self.uCategoryBox = QtWidgets.QComboBox(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uCategoryBox.sizePolicy().hasHeightForWidth())
        self.uCategoryBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uCategoryBox.setFont(font)
        self.uCategoryBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uCategoryBox.setStyleSheet("")
        self.uCategoryBox.setObjectName("uCategoryBox")
        self.uCategoryBox.addItem("")
        self.uCategoryContainer.addWidget(self.uCategoryBox)
        self.uCategoryNewLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uCategoryNewLabel.setFont(font)
        self.uCategoryNewLabel.setObjectName("uCategoryNewLabel")
        self.uCategoryContainer.addWidget(self.uCategoryNewLabel)
        self.uCategoryField = QtWidgets.QLineEdit(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uCategoryField.setFont(font)
        self.uCategoryField.setObjectName("uCategoryField")
        self.uCategoryContainer.addWidget(self.uCategoryField)
        self.gridLayout_5.addLayout(self.uCategoryContainer, 6, 1, 1, 3)
        self.uPasswordField = QtWidgets.QLineEdit(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uPasswordField.setFont(font)
        self.uPasswordField.setText("")
        self.uPasswordField.setObjectName("uPasswordField")
        self.gridLayout_5.addWidget(self.uPasswordField, 5, 1, 1, 3)
        self.uDescriptionLabel = QtWidgets.QLabel(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uDescriptionLabel.sizePolicy().hasHeightForWidth())
        self.uDescriptionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uDescriptionLabel.setFont(font)
        self.uDescriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uDescriptionLabel.setObjectName("uDescriptionLabel")
        self.gridLayout_5.addWidget(self.uDescriptionLabel, 1, 0, 1, 1)
        self.uTagLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTagLabel.setFont(font)
        self.uTagLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uTagLabel.setObjectName("uTagLabel")
        self.gridLayout_5.addWidget(self.uTagLabel, 7, 0, 1, 1)
        self.uTargetField = QtWidgets.QLineEdit(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTargetField.setFont(font)
        self.uTargetField.setText("")
        self.uTargetField.setObjectName("uTargetField")
        self.gridLayout_5.addWidget(self.uTargetField, 2, 1, 1, 3)
        self.uTargetLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTargetLabel.setFont(font)
        self.uTargetLabel.setObjectName("uTargetLabel")
        self.gridLayout_5.addWidget(self.uTargetLabel, 2, 0, 1, 1)
        self.uTitleField = QtWidgets.QLineEdit(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTitleField.setFont(font)
        self.uTitleField.setText("")
        self.uTitleField.setObjectName("uTitleField")
        self.gridLayout_5.addWidget(self.uTitleField, 0, 1, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 11, 2, 1, 1)
        self.uColorLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uColorLabel.setFont(font)
        self.uColorLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.uColorLabel.setObjectName("uColorLabel")
        self.gridLayout_5.addWidget(self.uColorLabel, 9, 0, 1, 1)
        self.uUsernameLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uUsernameLabel.setFont(font)
        self.uUsernameLabel.setObjectName("uUsernameLabel")
        self.gridLayout_5.addWidget(self.uUsernameLabel, 4, 0, 1, 1)
        self.uTagContainer = QtWidgets.QVBoxLayout()
        self.uTagContainer.setObjectName("uTagContainer")
        self.uTagCheck1 = QtWidgets.QCheckBox(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTagCheck1.setFont(font)
        self.uTagCheck1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uTagCheck1.setObjectName("uTagCheck1")
        self.uTagContainer.addWidget(self.uTagCheck1)
        self.uTagField = QtWidgets.QLineEdit(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uTagField.sizePolicy().hasHeightForWidth())
        self.uTagField.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTagField.setFont(font)
        self.uTagField.setObjectName("uTagField")
        self.uTagContainer.addWidget(self.uTagField)
        self.uTagBtn = QtWidgets.QPushButton(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uTagBtn.sizePolicy().hasHeightForWidth())
        self.uTagBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTagBtn.setFont(font)
        self.uTagBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uTagBtn.setStyleSheet("QPushButton{\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"}")
        self.uTagBtn.setObjectName("uTagBtn")
        self.uTagContainer.addWidget(self.uTagBtn)
        self.gridLayout_5.addLayout(self.uTagContainer, 7, 1, 1, 1)
        self.uCancelBtn = QtWidgets.QPushButton(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uCancelBtn.sizePolicy().hasHeightForWidth())
        self.uCancelBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uCancelBtn.setFont(font)
        self.uCancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uCancelBtn.setStyleSheet("QPushButton{\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius:5px;\n"
"}")
        self.uCancelBtn.setObjectName("uCancelBtn")
        self.gridLayout_5.addWidget(self.uCancelBtn, 12, 3, 1, 1)
        self.uPasswordLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uPasswordLabel.setFont(font)
        self.uPasswordLabel.setObjectName("uPasswordLabel")
        self.gridLayout_5.addWidget(self.uPasswordLabel, 5, 0, 1, 1)
        self.uCategoryLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uCategoryLabel.setFont(font)
        self.uCategoryLabel.setObjectName("uCategoryLabel")
        self.gridLayout_5.addWidget(self.uCategoryLabel, 6, 0, 1, 1)
        self.uTypeLabel = QtWidgets.QLabel(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTypeLabel.setFont(font)
        self.uTypeLabel.setObjectName("uTypeLabel")
        self.gridLayout_5.addWidget(self.uTypeLabel, 8, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 10, 1, 1, 1)
        self.uColorContainer = QtWidgets.QVBoxLayout()
        self.uColorContainer.setObjectName("uColorContainer")
        self.uColorBox = QtWidgets.QComboBox(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uColorBox.sizePolicy().hasHeightForWidth())
        self.uColorBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uColorBox.setFont(font)
        self.uColorBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uColorBox.setObjectName("uColorBox")
        self.uColorBox.addItem("")
        self.uColorContainer.addWidget(self.uColorBox)
        self.uColorField = QtWidgets.QLineEdit(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uColorField.sizePolicy().hasHeightForWidth())
        self.uColorField.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uColorField.setFont(font)
        self.uColorField.setObjectName("uColorField")
        self.uColorContainer.addWidget(self.uColorField)
        self.uColorBtn = QtWidgets.QPushButton(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uColorBtn.sizePolicy().hasHeightForWidth())
        self.uColorBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uColorBtn.setFont(font)
        self.uColorBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uColorBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"}")
        self.uColorBtn.setObjectName("uColorBtn")
        self.uColorContainer.addWidget(self.uColorBtn)
        self.gridLayout_5.addLayout(self.uColorContainer, 9, 1, 1, 1)
        self.uUpdateBtn = QtWidgets.QPushButton(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uUpdateBtn.sizePolicy().hasHeightForWidth())
        self.uUpdateBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uUpdateBtn.setFont(font)
        self.uUpdateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uUpdateBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius:5px;\n"
"}")
        self.uUpdateBtn.setObjectName("uUpdateBtn")
        self.gridLayout_5.addWidget(self.uUpdateBtn, 12, 2, 1, 1)
        self.uTitleLabel = QtWidgets.QLabel(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uTitleLabel.sizePolicy().hasHeightForWidth())
        self.uTitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTitleLabel.setFont(font)
        self.uTitleLabel.setObjectName("uTitleLabel")
        self.gridLayout_5.addWidget(self.uTitleLabel, 0, 0, 1, 1)
        self.uTypeBox = QtWidgets.QComboBox(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uTypeBox.sizePolicy().hasHeightForWidth())
        self.uTypeBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uTypeBox.setFont(font)
        self.uTypeBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uTypeBox.setObjectName("uTypeBox")
        self.uTypeBox.addItem("")
        self.uTypeBox.addItem("")
        self.uTypeBox.addItem("")
        self.uTypeBox.addItem("")
        self.gridLayout_5.addWidget(self.uTypeBox, 8, 1, 1, 1)
        self.uUsernameField = QtWidgets.QLineEdit(self.uRMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.uUsernameField.setFont(font)
        self.uUsernameField.setText("")
        self.uUsernameField.setObjectName("uUsernameField")
        self.gridLayout_5.addWidget(self.uUsernameField, 4, 1, 1, 3)
        self.uDescriptionField = QtWidgets.QPlainTextEdit(self.uRMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uDescriptionField.sizePolicy().hasHeightForWidth())
        self.uDescriptionField.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.uDescriptionField.setFont(font)
        self.uDescriptionField.setStyleSheet("font: 12pt \"Arial\";")
        self.uDescriptionField.setPlainText("")
        self.uDescriptionField.setObjectName("uDescriptionField")
        self.gridLayout_5.addWidget(self.uDescriptionField, 1, 1, 1, 3)
        self.uRMain.setWidget(self.uRMainContent)
        self.uMain.addWidget(self.uRMain)
        self.verticalLayout_6.addLayout(self.uMain)
        self.parentWidget.addWidget(self.vaultU)
        self.vaultC = QtWidgets.QWidget()
        self.vaultC.setObjectName("vaultC")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.vaultC)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cTopNB = QtWidgets.QHBoxLayout()
        self.cTopNB.setSpacing(0)
        self.cTopNB.setObjectName("cTopNB")
        self.cCreateBtn = QtWidgets.QPushButton(self.vaultC)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cCreateBtn.setFont(font)
        self.cCreateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cCreateBtn.setStyleSheet("QPushButton{\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"    background-color: #34495E;\n"
"    color:rgb(255, 255, 255);\n"
"    font: 75 12pt \"Arial\";\n"
"}")
        self.cCreateBtn.setObjectName("cCreateBtn")
        self.cTopNB.addWidget(self.cCreateBtn)
        self.cVaultBtn = QtWidgets.QPushButton(self.vaultC)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cVaultBtn.setFont(font)
        self.cVaultBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cVaultBtn.setStyleSheet("QPushButton {\n"
"    background-color: #3A6187;\n"
"    color: #dfdfdf;\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"    font: 75 12pt \"Arial\";\n"
"}")
        self.cVaultBtn.setObjectName("cVaultBtn")
        self.cTopNB.addWidget(self.cVaultBtn)
        self.cSettingBtn = QtWidgets.QPushButton(self.vaultC)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cSettingBtn.sizePolicy().hasHeightForWidth())
        self.cSettingBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cSettingBtn.setFont(font)
        self.cSettingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cSettingBtn.setStyleSheet("QPushButton {\n"
"    padding: 10px 0px;\n"
"    border: none;\n"
"    padding: 10px 10px;\n"
"    background-color: #3A6187;\n"
"    font: 75 12pt \"Arial\";\n"
"    color:white;\n"
"}")
        self.cSettingBtn.setObjectName("cSettingBtn")
        self.cTopNB.addWidget(self.cSettingBtn)
        self.verticalLayout_7.addLayout(self.cTopNB)
        self.cTopLine = QtWidgets.QFrame(self.vaultC)
        self.cTopLine.setStyleSheet("background-color: #34495E;")
        self.cTopLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.cTopLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cTopLine.setObjectName("cTopLine")
        self.verticalLayout_7.addWidget(self.cTopLine)
        self.cMain = QtWidgets.QHBoxLayout()
        self.cMain.setContentsMargins(0, 0, 0, 0)
        self.cMain.setSpacing(10)
        self.cMain.setObjectName("cMain")
        self.cMainArea = QtWidgets.QScrollArea(self.vaultC)
        self.cMainArea.setStyleSheet("background-color: rgb(28, 40, 52);\n"
"color: #DFDFDF;")
        self.cMainArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cMainArea.setLineWidth(0)
        self.cMainArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cMainArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.cMainArea.setWidgetResizable(True)
        self.cMainArea.setObjectName("cMainArea")
        self.cMainContent = QtWidgets.QWidget()
        self.cMainContent.setGeometry(QtCore.QRect(0, 0, 400, 811))
        self.cMainContent.setObjectName("cMainContent")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.cMainContent)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cTitleLabel = QtWidgets.QLabel(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cTitleLabel.sizePolicy().hasHeightForWidth())
        self.cTitleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cTitleLabel.setFont(font)
        self.cTitleLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.cTitleLabel.setObjectName("cTitleLabel")
        self.gridLayout_6.addWidget(self.cTitleLabel, 0, 0, 1, 1)
        self.cTitleField = QtWidgets.QLineEdit(self.cMainContent)
        self.cTitleField.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cTitleField.setText("")
        self.cTitleField.setObjectName("cTitleField")
        self.gridLayout_6.addWidget(self.cTitleField, 1, 0, 1, 1)
        self.cDescriptionLabel = QtWidgets.QLabel(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cDescriptionLabel.sizePolicy().hasHeightForWidth())
        self.cDescriptionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cDescriptionLabel.setFont(font)
        self.cDescriptionLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cDescriptionLabel.setObjectName("cDescriptionLabel")
        self.gridLayout_6.addWidget(self.cDescriptionLabel, 4, 0, 1, 1)
        self.cUsernameLabel = QtWidgets.QLabel(self.cMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cUsernameLabel.setFont(font)
        self.cUsernameLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.cUsernameLabel.setObjectName("cUsernameLabel")
        self.gridLayout_6.addWidget(self.cUsernameLabel, 8, 0, 1, 1)
        self.cTagContainer = QtWidgets.QVBoxLayout()
        self.cTagContainer.setObjectName("cTagContainer")
        self.cTagLabel = QtWidgets.QLabel(self.cMainContent)
        self.cTagLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.cTagLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cTagLabel.setObjectName("cTagLabel")
        self.cTagContainer.addWidget(self.cTagLabel)
        self.cTagField = QtWidgets.QLineEdit(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cTagField.sizePolicy().hasHeightForWidth())
        self.cTagField.setSizePolicy(sizePolicy)
        self.cTagField.setStyleSheet("font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"")
        self.cTagField.setObjectName("cTagField")
        self.cTagContainer.addWidget(self.cTagField)
        self.cTagBtn = QtWidgets.QPushButton(self.cMainContent)
        self.cTagBtn.clicked.connect(self.addTag)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cTagBtn.sizePolicy().hasHeightForWidth())
        self.cTagBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cTagBtn.setFont(font)
        self.cTagBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cTagBtn.setStyleSheet("QPushButton{\n"
"    background-color: #3A6187;\n"
"    color:rgb(255, 255, 255);\n"
"    font: 12pt \"Arial\";\n"
"}")
        self.cTagBtn.setObjectName("cTagBtn")
        self.cTagContainer.addWidget(self.cTagBtn)
        self.gridLayout_6.addLayout(self.cTagContainer, 29, 0, 1, 1)
        self.cMainCreateBtn = QtWidgets.QPushButton(self.cMainContent)
        self.cMainCreateBtn.clicked.connect(self.onCreate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cMainCreateBtn.sizePolicy().hasHeightForWidth())
        self.cMainCreateBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cMainCreateBtn.setFont(font)
        self.cMainCreateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cMainCreateBtn.setStyleSheet("QPushButton{\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius:5px;\n"
"}")
        self.cMainCreateBtn.setObjectName("cMainCreateBtn")
        self.gridLayout_6.addWidget(self.cMainCreateBtn, 37, 1, 1, 1)
        self.cDescriptionField = QtWidgets.QPlainTextEdit(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cDescriptionField.sizePolicy().hasHeightForWidth())
        self.cDescriptionField.setSizePolicy(sizePolicy)
        self.cDescriptionField.setStyleSheet("font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);")
        self.cDescriptionField.setPlainText("")
        self.cDescriptionField.setObjectName("cDescriptionField")
        self.gridLayout_6.addWidget(self.cDescriptionField, 5, 0, 1, 3)
        self.cCategoryLabel = QtWidgets.QLabel(self.cMainContent)
        self.cCategoryLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cCategoryLabel.setObjectName("cCategoryLabel")
        self.gridLayout_6.addWidget(self.cCategoryLabel, 17, 0, 1, 1)
        self.cCategoryField = QtWidgets.QLineEdit(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cCategoryField.sizePolicy().hasHeightForWidth())
        self.cCategoryField.setSizePolicy(sizePolicy)
        self.cCategoryField.setStyleSheet("font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"")
        self.cCategoryField.setObjectName("cCategoryField")
        self.gridLayout_6.addWidget(self.cCategoryField, 18, 2, 1, 1)
        self.cCategoryLabel2 = QtWidgets.QLabel(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cCategoryLabel2.sizePolicy().hasHeightForWidth())
        self.cCategoryLabel2.setSizePolicy(sizePolicy)
        self.cCategoryLabel2.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cCategoryLabel2.setObjectName("cCategoryLabel2")
        self.gridLayout_6.addWidget(self.cCategoryLabel2, 17, 2, 1, 1)
        self.cTargetField = QtWidgets.QLineEdit(self.cMainContent)
        self.cTargetField.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cTargetField.setText("")
        self.cTargetField.setObjectName("cTargetField")
        self.gridLayout_6.addWidget(self.cTargetField, 1, 2, 1, 1)
        self.cTargetLabel = QtWidgets.QLabel(self.cMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cTargetLabel.setFont(font)
        self.cTargetLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.cTargetLabel.setObjectName("cTargetLabel")
        self.gridLayout_6.addWidget(self.cTargetLabel, 0, 2, 1, 1)
        self.cCancelBtn = QtWidgets.QPushButton(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cCancelBtn.sizePolicy().hasHeightForWidth())
        self.cCancelBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cCancelBtn.setFont(font)
        self.cCancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cCancelBtn.setStyleSheet("QPushButton{\n"
"    background-color: #3A6187;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #dfdfdf;\n"
"    color:black;\n"
"    border-radius:5px;\n"
"}")
        self.cCancelBtn.setObjectName("cCancelBtn")
        self.gridLayout_6.addWidget(self.cCancelBtn, 37, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem14, 36, 1, 1, 1)
        self.cTypeBox = QtWidgets.QComboBox(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cTypeBox.sizePolicy().hasHeightForWidth())
        self.cTypeBox.setSizePolicy(sizePolicy)
        self.cTypeBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cTypeBox.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"")
        self.cTypeBox.setObjectName("cTypeBox")
        self.cTypeBox.addItem("")
        self.cTypeBox.addItem("")
        self.cTypeBox.addItem("")
        self.cTypeBox.addItem("")
        self.gridLayout_6.addWidget(self.cTypeBox, 32, 0, 1, 1)
        self.cCategoryBox = QtWidgets.QComboBox(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cCategoryBox.sizePolicy().hasHeightForWidth())
        self.cCategoryBox.setSizePolicy(sizePolicy)
        self.cCategoryBox.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cCategoryBox.setObjectName("cCategoryBox")
        self.gridLayout_6.addWidget(self.cCategoryBox, 18, 0, 1, 1)
        self.cUsernameField = QtWidgets.QLineEdit(self.cMainContent)
        self.cUsernameField.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cUsernameField.setText("")
        self.cUsernameField.setObjectName("cUsernameField")
        self.gridLayout_6.addWidget(self.cUsernameField, 9, 0, 1, 1)
        self.cColorContainer = QtWidgets.QVBoxLayout()
        self.cColorContainer.setObjectName("cColorContainer")
        self.cColorLabel = QtWidgets.QLabel(self.cMainContent)
        self.cColorLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.cColorLabel.setObjectName("cColorLabel")
        self.cColorContainer.addWidget(self.cColorLabel)
        self.cColorBox = QtWidgets.QComboBox(self.cMainContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cColorBox.sizePolicy().hasHeightForWidth())
        self.cColorBox.setSizePolicy(sizePolicy)
        self.cColorBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cColorBox.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"\n"
"")
        self.cColorBox.setObjectName("cColorBox")
        self.cColorBox.addItems(["Red" "Blue", "Yellow", "Green"])
        self.cColorContainer.addWidget(self.cColorBox)
        self.gridLayout_6.addLayout(self.cColorContainer, 29, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem15, 6, 0, 1, 1)
        self.cTypeLabel = QtWidgets.QLabel(self.cMainContent)
        self.cTypeLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.cTypeLabel.setObjectName("cTypeLabel")
        self.gridLayout_6.addWidget(self.cTypeLabel, 31, 0, 1, 1)
        self.cPasswordField = QtWidgets.QLineEdit(self.cMainContent)
        self.cPasswordField.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cPasswordField.setText("")
        self.cPasswordField.setObjectName("cPasswordField")
        self.gridLayout_6.addWidget(self.cPasswordField, 9, 2, 1, 1)
        self.cPasswordLabel = QtWidgets.QLabel(self.cMainContent)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cPasswordLabel.setFont(font)
        self.cPasswordLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.cPasswordLabel.setObjectName("cPasswordLabel")
        self.gridLayout_6.addWidget(self.cPasswordLabel, 8, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem16, 30, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem17, 10, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem18, 19, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem19, 3, 0, 1, 1)
        self.cMainArea.setWidget(self.cMainContent)
        self.cMain.addWidget(self.cMainArea)
        self.verticalLayout_7.addLayout(self.cMain)
        self.parentWidget.addWidget(self.vaultC)
        self.horizontalLayout.addWidget(self.parentWidget)

        self.retranslateUi(storageDark)
        self.parentWidget.setCurrentIndex(0)
        self.uVaultBtn.clicked.connect(lambda: self.update(0, "CancelUpdate"))
        self.uCreateBtn.clicked.connect(lambda: self.update(2, "CancelUpdate"))
        self.uUpdateBtn.clicked.connect(lambda: self.update(0, "Update"))
        self.uCancelBtn.clicked.connect(lambda: self.update(0, "CancelUpdate"))
        self.vCreateBtn.clicked.connect(lambda: self.update(2, "Create"))
        self.vVaultBtn.clicked.connect(lambda: self.update(0))
        self.vEditBtn.clicked.connect(lambda: self.update(1))
        self.cCreateBtn.clicked.connect(lambda: self.update(2))
        self.cVaultBtn.clicked.connect(lambda: self.update(0, "CancelCreate"))
        self.cMainCreateBtn.clicked.connect(lambda: self.update(0, "CreateUpload"))
        self.cCancelBtn.clicked.connect(lambda: self.update(0, "CancelCreate"))
        QtCore.QMetaObject.connectSlotsByName(storageDark)

    def retranslateUi(self, storageDark):
        _translate = QtCore.QCoreApplication.translate
        storageDark.setWindowTitle(_translate("storageDark", "Form"))
        self.vCreateBtn.setText(_translate("storageDark", "Create"))
        self.vVaultBtn.setText(_translate("storageDark", "Vault"))
        self.vSettingBtn.setText(_translate("storageDark", "Setting"))
        self.vLMFilterLabel.setText(_translate("storageDark", "Filter"))
        self.vLMFilterBox.setItemText(0, _translate("storageDark", "A-Z"))
        self.vLMFilterBox.setItemText(1, _translate("storageDark", "Z-A"))
        self.vLMFilterBox.setItemText(2, _translate("storageDark", "Highest Priority"))
        self.vLMFilterBox.setItemText(3, _translate("storageDark", "Lowest Priority"))
        self.vLMSearchLabel.setText(_translate("storageDark", "Search"))
        self.vLMSearchBox.setItemText(0, _translate("storageDark", "Relevance"))
        self.vLMSearchBox.setItemText(1, _translate("storageDark", "Categories"))
        self.vLMSearchBox.setItemText(2, _translate("storageDark", "Tags"))
        self.vLMSearchBox.setItemText(3, _translate("storageDark", "Types"))
        self.vLMSearchBox.setItemText(4, _translate("storageDark", "Colors"))
        self.deleteBtn.setText(_translate("storageDark", "Delete"))
        self.vEditBtn.setText(_translate("storageDark", "Edit"))
        self.vColor.setText(_translate("storageDark", "warna"))
        self.vUsername.setText(_translate("storageDark", "lolthisisnotmyemail@gmail.com"))
        self.vCategory.setText(_translate("storageDark", "kategori1"))
        self.vDescription.setText(_translate("storageDark", "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."))
        self.vTypes.setText(_translate("storageDark", "Very Important"))
        self.vPassword.setText(_translate("storageDark", "myverysecurepassword"))
        self.vTitle.setText(_translate("storageDark", "Header/Judul"))
        self.vTarget.setText(_translate("storageDark", "www.google.com"))
        self.uCreateBtn.setText(_translate("storageDark", "Create"))
        self.uVaultBtn.setText(_translate("storageDark", "Vault"))
        self.uSettingBtn.setText(_translate("storageDark", "Setting"))
        self.uLMFilterLabel.setText(_translate("storageDark", "Filter"))
        self.uLMFilterBox.setItemText(0, _translate("storageDark", "A-Z"))
        self.uLMFilterBox.setItemText(1, _translate("storageDark", "Z-A"))
        self.uLMFilterBox.setItemText(2, _translate("storageDark", "Highest Priority"))
        self.uLMFilterBox.setItemText(3, _translate("storageDark", "Lowest Priority"))
        self.uLMSearchLabel.setText(_translate("storageDark", "Search"))
        self.uLMSearchBox.setItemText(0, _translate("storageDark", "Relevance"))
        self.uLMSearchBox.setItemText(1, _translate("storageDark", "Categories"))
        self.uLMSearchBox.setItemText(2, _translate("storageDark", "Tags"))
        self.uLMSearchBox.setItemText(3, _translate("storageDark", "Types"))
        self.uLMSearchBox.setItemText(4, _translate("storageDark", "Colors"))
        self.uLMBoxItem1.setText(_translate("storageDark", "PushButton"))
        self.uCategoryBox.setItemText(0, _translate("storageDark", "cat"))
        self.uCategoryNewLabel.setText(_translate("storageDark", "Or New: "))
        self.uPasswordField.setPlaceholderText(_translate("storageDark", "Password"))
        self.uDescriptionLabel.setText(_translate("storageDark", "Description"))
        self.uTagLabel.setText(_translate("storageDark", "Tags"))
        self.uTargetField.setPlaceholderText(_translate("storageDark", "Target"))
        self.uTargetLabel.setText(_translate("storageDark", "Target"))
        self.uTitleField.setPlaceholderText(_translate("storageDark", "Title"))
        self.uColorLabel.setText(_translate("storageDark", "Color"))
        self.uUsernameLabel.setText(_translate("storageDark", "Username"))
        self.uTagCheck1.setText(_translate("storageDark", "CheckBox"))
        self.uTagBtn.setText(_translate("storageDark", "Add +"))
        self.uCancelBtn.setText(_translate("storageDark", "Cancel"))
        self.uPasswordLabel.setText(_translate("storageDark", "Password"))
        self.uCategoryLabel.setText(_translate("storageDark", "Categories"))
        self.uTypeLabel.setText(_translate("storageDark", "Types"))
        self.uColorBox.setItemText(0, _translate("storageDark", "Red"))
        self.uColorBtn.setText(_translate("storageDark", "New Color ..."))
        self.uUpdateBtn.setText(_translate("storageDark", "Update"))
        self.uTitleLabel.setText(_translate("storageDark", "Title"))
        self.uTypeBox.setItemText(0, _translate("storageDark", "Very Important"))
        self.uTypeBox.setItemText(1, _translate("storageDark", "Important"))
        self.uTypeBox.setItemText(2, _translate("storageDark", "Middle Important"))
        self.uTypeBox.setItemText(3, _translate("storageDark", "Regular"))
        self.uUsernameField.setPlaceholderText(_translate("storageDark", "Username"))
        self.uDescriptionField.setPlaceholderText(_translate("storageDark", "Description"))
        self.cCreateBtn.setText(_translate("storageDark", "Create"))
        self.cVaultBtn.setText(_translate("storageDark", "Vault"))
        self.cSettingBtn.setText(_translate("storageDark", "Setting"))
        self.cTitleLabel.setText(_translate("storageDark", "Title"))
        self.cTitleField.setPlaceholderText(_translate("storageDark", "Title"))
        self.cDescriptionLabel.setText(_translate("storageDark", "Description"))
        self.cUsernameLabel.setText(_translate("storageDark", "Username"))
        self.cTagLabel.setText(_translate("storageDark", "Tags"))
        self.cTagBtn.setText(_translate("storageDark", "Add +"))
        self.cMainCreateBtn.setText(_translate("storageDark", "Create"))
        self.cDescriptionField.setPlaceholderText(_translate("storageDark", "Description"))
        self.cCategoryLabel.setText(_translate("storageDark", "Categories"))
        self.cCategoryLabel2.setText(_translate("storageDark", "Or New"))
        self.cTargetField.setPlaceholderText(_translate("storageDark", "Target"))
        self.cTargetLabel.setText(_translate("storageDark", "Target"))
        self.cCancelBtn.setText(_translate("storageDark", "Cancel"))
        self.cTypeBox.setItemText(0, _translate("storageDark", "Very Important"))
        self.cTypeBox.setItemText(1, _translate("storageDark", "Important"))
        self.cTypeBox.setItemText(2, _translate("storageDark", "Middle Important"))
        self.cTypeBox.setItemText(3, _translate("storageDark", "Regular"))
        self.cUsernameField.setPlaceholderText(_translate("storageDark", "Username"))
        self.cColorLabel.setText(_translate("storageDark", "Color"))
        self.cTypeLabel.setText(_translate("storageDark", "Types"))
        self.cPasswordField.setPlaceholderText(_translate("storageDark", "Password"))
        self.cPasswordLabel.setText(_translate("storageDark", "Password"))
        self.setItemSideBar()

        self.vTitle.hide()
        self.vUsername.hide()
        self.vPassword.hide()
        self.vTarget.hide()
        self.vDescription.hide()
        self.vCategory.hide()
        self.vTypes.hide()
        self.vColor.hide()
        self.vEditBtn.hide()
        self.deleteBtn.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    storageDark = QtWidgets.QWidget()
    ui = Ui_storageDark()
    ui.setupUi(storageDark)
    storageDark.show()
    sys.exit(app.exec_())
