# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'darkcreatenew.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedWidth(400)
        Form.setFixedHeight(850)
        Form.setStyleSheet("* {\n"
"    font: 75 11pt \"Arial\";\n"
"}\n"
"QLabel#appName {\n"
"    font: 75 36pt \"Arial\";\n"
"}\n"
"QLabel#appName_2 {\n"
"    font: 75 36pt \"Arial\";\n"
"}\n"
"QLabel#appName_4 {\n"
"    font: 75 36pt \"Arial\";\n"
"}\n"
"QLabel#appName_5 {\n"
"    font: 75 36pt \"Arial\";\n"
"}\n"
"QLabel#versionName {\n"
"    padding: 0px 0px 20px;\n"
"}\n"
"QLabel#versionName_2 {\n"
"    padding: 0px 0px 20px;\n"
"}\n"
"QLabel#versionName_4 {\n"
"    padding: 0px 0px 20px;\n"
"}\n"
"QLabel#versionName_5 {\n"
"    padding: 0px 0px 20px;\n"
"}\n"
"QLineEdit {\n"
"    padding: 4px;\n"
"    border: 2px solid rgb(120, 120, 120);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(57, 136, 255);\n"
"}\n"
"QCheckBox {\n"
"    padding: 10px 0px 10px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setMaximumSize(QtCore.QSize(500, 900))
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topLayoutGroup = QtWidgets.QGroupBox(self.page1)
        self.topLayoutGroup.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.topLayoutGroup.setObjectName("topLayoutGroup")
        self.topLayout = QtWidgets.QGridLayout(self.topLayoutGroup)
        self.topLayout.setContentsMargins(0, 0, 0, 0)
        self.topLayout.setSpacing(0)
        self.topLayout.setObjectName("topLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout.addItem(spacerItem1, 6, 1, 1, 1)
        self.imageLabel = QtWidgets.QLabel(self.topLayoutGroup)
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap("resources/reavaultDark.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.topLayout.addWidget(self.imageLabel, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.appName = QtWidgets.QLabel(self.topLayoutGroup)
        self.appName.setStyleSheet("color: rgb(255, 255, 255);")
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName("appName")
        self.topLayout.addWidget(self.appName, 3, 1, 1, 1)
        self.versionName = QtWidgets.QLabel(self.topLayoutGroup)
        self.versionName.setStyleSheet("color: rgb(255, 255, 255);")
        self.versionName.setAlignment(QtCore.Qt.AlignCenter)
        self.versionName.setObjectName("versionName")
        self.topLayout.addWidget(self.versionName, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.topLayoutGroup)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.topLayout.addWidget(self.label, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.topLayoutGroup)
        self.bottomLayoutGroup = QtWidgets.QGroupBox(self.page1)
        self.bottomLayoutGroup.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.bottomLayoutGroup.setObjectName("bottomLayoutGroup")
        self.bottomLayout = QtWidgets.QGridLayout(self.bottomLayoutGroup)
        self.bottomLayout.setContentsMargins(0, 0, 0, 0)
        self.bottomLayout.setSpacing(0)
        self.bottomLayout.setObjectName("bottomLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout.addItem(spacerItem4, 9, 1, 1, 1)
        self.confLabel = QtWidgets.QLabel(self.bottomLayoutGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confLabel.sizePolicy().hasHeightForWidth())
        self.confLabel.setSizePolicy(sizePolicy)
        self.confLabel.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.confLabel.setObjectName("confLabel")
        self.bottomLayout.addWidget(self.confLabel, 5, 1, 1, 1)
        self.nextBtn = QtWidgets.QPushButton(self.bottomLayoutGroup)
        self.nextBtn.setStyleSheet("QPushButton{\n"
"    margin: 10px 60px 0px;\n"
"    padding: 10px 0px 10px;\n"
"    background-color: #2861b6;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(47, 117, 214);\n"
"}")
        self.nextBtn.setObjectName("nextBtn")
        self.bottomLayout.addWidget(self.nextBtn, 8, 1, 1, 1)
        self.confField = QtWidgets.QLineEdit(self.bottomLayoutGroup)
        self.confField.setStyleSheet("color: rgb(255, 255, 255);")
        self.confField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confField.setObjectName("confField")
        self.bottomLayout.addWidget(self.confField, 6, 1, 1, 1)
        self.isVisible = QtWidgets.QCheckBox(self.bottomLayoutGroup)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.isVisible.setFont(font)
        self.isVisible.setStyleSheet("font: 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.isVisible.setObjectName("isVisible")
        self.bottomLayout.addWidget(self.isVisible, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.userLabel = QtWidgets.QLabel(self.bottomLayoutGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userLabel.sizePolicy().hasHeightForWidth())
        self.userLabel.setSizePolicy(sizePolicy)
        self.userLabel.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.userLabel.setObjectName("userLabel")
        self.bottomLayout.addWidget(self.userLabel, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem5, 8, 0, 1, 1)
        self.passLabel = QtWidgets.QLabel(self.bottomLayoutGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passLabel.sizePolicy().hasHeightForWidth())
        self.passLabel.setSizePolicy(sizePolicy)
        self.passLabel.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.passLabel.setObjectName("passLabel")
        self.bottomLayout.addWidget(self.passLabel, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem7, 8, 2, 1, 1)
        self.passField = QtWidgets.QLineEdit(self.bottomLayoutGroup)
        self.passField.setStyleSheet("color: rgb(255, 255, 255);")
        self.passField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passField.setObjectName("passField")
        self.bottomLayout.addWidget(self.passField, 4, 1, 1, 1)
        self.userField = QtWidgets.QLineEdit(self.bottomLayoutGroup)
        self.userField.setStyleSheet("color: rgb(255, 255, 255);")
        self.userField.setObjectName("userField")
        self.bottomLayout.addWidget(self.userField, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.bottomLayoutGroup)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLayoutGroup_2 = QtWidgets.QGroupBox(self.page2)
        self.topLayoutGroup_2.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.topLayoutGroup_2.setObjectName("topLayoutGroup_2")
        self.topLayout_2 = QtWidgets.QGridLayout(self.topLayoutGroup_2)
        self.topLayout_2.setContentsMargins(0, 0, 0, 0)
        self.topLayout_2.setSpacing(0)
        self.topLayout_2.setObjectName("topLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_2.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_2.addItem(spacerItem9, 6, 1, 1, 1)
        self.imageLabel_2 = QtWidgets.QLabel(self.topLayoutGroup_2)
        self.imageLabel_2.setText("")
        self.imageLabel_2.setPixmap(QtGui.QPixmap("resources/reavaultDark.png"))
        self.imageLabel_2.setScaledContents(True)
        self.imageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel_2.setObjectName("imageLabel_2")
        self.topLayout_2.addWidget(self.imageLabel_2, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_2.addItem(spacerItem10, 1, 2, 1, 1)
        self.appName_2 = QtWidgets.QLabel(self.topLayoutGroup_2)
        self.appName_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.appName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.appName_2.setObjectName("appName_2")
        self.topLayout_2.addWidget(self.appName_2, 3, 1, 1, 1)
        self.versionName_2 = QtWidgets.QLabel(self.topLayoutGroup_2)
        self.versionName_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.versionName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.versionName_2.setObjectName("versionName_2")
        self.topLayout_2.addWidget(self.versionName_2, 4, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_2.addItem(spacerItem11, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.topLayoutGroup_2)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.topLayout_2.addWidget(self.label_2, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.topLayoutGroup_2)
        self.bottomLayoutGroup_2 = QtWidgets.QGroupBox(self.page2)
        self.bottomLayoutGroup_2.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.bottomLayoutGroup_2.setObjectName("bottomLayoutGroup_2")
        self.bottomLayout_2 = QtWidgets.QGridLayout(self.bottomLayoutGroup_2)
        self.bottomLayout_2.setContentsMargins(0, 0, 0, 0)
        self.bottomLayout_2.setSpacing(0)
        self.bottomLayout_2.setObjectName("bottomLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_2.addItem(spacerItem12, 6, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_2.addItem(spacerItem13, 7, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.bottomLayoutGroup_2)
        self.comboBox.setObjectName("comboBox")
        self.bottomLayout_2.addWidget(self.comboBox, 2, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_2.addItem(spacerItem14, 8, 1, 1, 1)
        self.confLabel_2 = QtWidgets.QLabel(self.bottomLayoutGroup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confLabel_2.sizePolicy().hasHeightForWidth())
        self.confLabel_2.setSizePolicy(sizePolicy)
        self.confLabel_2.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.confLabel_2.setObjectName("confLabel_2")
        self.bottomLayout_2.addWidget(self.confLabel_2, 3, 1, 1, 1)
        self.nextBtn2 = QtWidgets.QPushButton(self.bottomLayoutGroup_2)
        self.nextBtn2.setStyleSheet("QPushButton{\n"
"    margin: 10px 60px 0px;\n"
"    padding: 10px 0px 10px;\n"
"    background-color: #2861b6;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(47, 117, 214);\n"
"}")
        self.nextBtn2.setObjectName("nextBtn2")
        self.bottomLayout_2.addWidget(self.nextBtn2, 7, 1, 1, 1)
        self.passLabel_2 = QtWidgets.QLabel(self.bottomLayoutGroup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passLabel_2.sizePolicy().hasHeightForWidth())
        self.passLabel_2.setSizePolicy(sizePolicy)
        self.passLabel_2.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.passLabel_2.setObjectName("passLabel_2")
        self.bottomLayout_2.addWidget(self.passLabel_2, 1, 1, 1, 1)
        self.confField_2 = QtWidgets.QLineEdit(self.bottomLayoutGroup_2)
        self.confField_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.confField_2.setObjectName("confField_2")
        self.bottomLayout_2.addWidget(self.confField_2, 4, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_2.addItem(spacerItem15, 7, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_2.addItem(spacerItem16, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_2.addItem(spacerItem17, 5, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.bottomLayoutGroup_2)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topLayoutGroup_3 = QtWidgets.QGroupBox(self.page3)
        self.topLayoutGroup_3.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.topLayoutGroup_3.setObjectName("topLayoutGroup_3")
        self.topLayout_4 = QtWidgets.QGridLayout(self.topLayoutGroup_3)
        self.topLayout_4.setContentsMargins(0, 0, 0, 0)
        self.topLayout_4.setSpacing(0)
        self.topLayout_4.setObjectName("topLayout_4")
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_4.addItem(spacerItem18, 0, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_4.addItem(spacerItem19, 6, 1, 1, 1)
        self.imageLabel_4 = QtWidgets.QLabel(self.topLayoutGroup_3)
        self.imageLabel_4.setText("")
        self.imageLabel_4.setPixmap(QtGui.QPixmap("resources/reavaultDark.png"))
        self.imageLabel_4.setScaledContents(True)
        self.imageLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel_4.setObjectName("imageLabel_4")
        self.topLayout_4.addWidget(self.imageLabel_4, 1, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_4.addItem(spacerItem20, 1, 2, 1, 1)
        self.appName_4 = QtWidgets.QLabel(self.topLayoutGroup_3)
        self.appName_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.appName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.appName_4.setObjectName("appName_4")
        self.topLayout_4.addWidget(self.appName_4, 3, 1, 1, 1)
        self.versionName_4 = QtWidgets.QLabel(self.topLayoutGroup_3)
        self.versionName_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.versionName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.versionName_4.setObjectName("versionName_4")
        self.topLayout_4.addWidget(self.versionName_4, 4, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_4.addItem(spacerItem21, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.topLayoutGroup_3)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.topLayout_4.addWidget(self.label_4, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.topLayoutGroup_3)
        self.bottomLayoutGroup_3 = QtWidgets.QGroupBox(self.page3)
        self.bottomLayoutGroup_3.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.bottomLayoutGroup_3.setObjectName("bottomLayoutGroup_3")
        self.bottomLayout_3 = QtWidgets.QGridLayout(self.bottomLayoutGroup_3)
        self.bottomLayout_3.setContentsMargins(0, 0, 0, 0)
        self.bottomLayout_3.setSpacing(0)
        self.bottomLayout_3.setObjectName("bottomLayout_3")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_3.addItem(spacerItem22, 6, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_3.addItem(spacerItem23, 7, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.bottomLayoutGroup_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.bottomLayout_3.addWidget(self.comboBox_2, 2, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_3.addItem(spacerItem24, 8, 1, 1, 1)
        self.confLabel_3 = QtWidgets.QLabel(self.bottomLayoutGroup_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confLabel_3.sizePolicy().hasHeightForWidth())
        self.confLabel_3.setSizePolicy(sizePolicy)
        self.confLabel_3.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.confLabel_3.setObjectName("confLabel_3")
        self.bottomLayout_3.addWidget(self.confLabel_3, 3, 1, 1, 1)
        self.nextBtn2_2 = QtWidgets.QPushButton(self.bottomLayoutGroup_3)
        self.nextBtn2_2.setStyleSheet("QPushButton{\n"
"    margin: 10px 60px 0px;\n"
"    padding: 10px 0px 10px;\n"
"    background-color: #2861b6;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(47, 117, 214);\n"
"}")
        self.nextBtn2_2.setObjectName("nextBtn2_2")
        self.bottomLayout_3.addWidget(self.nextBtn2_2, 7, 1, 1, 1)
        self.passLabel_3 = QtWidgets.QLabel(self.bottomLayoutGroup_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passLabel_3.sizePolicy().hasHeightForWidth())
        self.passLabel_3.setSizePolicy(sizePolicy)
        self.passLabel_3.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.passLabel_3.setObjectName("passLabel_3")
        self.bottomLayout_3.addWidget(self.passLabel_3, 1, 1, 1, 1)
        self.confField_3 = QtWidgets.QLineEdit(self.bottomLayoutGroup_3)
        self.confField_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.confField_3.setObjectName("confField_3")
        self.bottomLayout_3.addWidget(self.confField_3, 4, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_3.addItem(spacerItem25, 7, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_3.addItem(spacerItem26, 0, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_3.addItem(spacerItem27, 5, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.bottomLayoutGroup_3)
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topLayoutGroup_4 = QtWidgets.QGroupBox(self.page4)
        self.topLayoutGroup_4.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.topLayoutGroup_4.setObjectName("topLayoutGroup_4")
        self.topLayout_5 = QtWidgets.QGridLayout(self.topLayoutGroup_4)
        self.topLayout_5.setContentsMargins(0, 0, 0, 0)
        self.topLayout_5.setSpacing(0)
        self.topLayout_5.setObjectName("topLayout_5")
        spacerItem28 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_5.addItem(spacerItem28, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.topLayout_5.addItem(spacerItem29, 6, 1, 1, 1)
        self.imageLabel_5 = QtWidgets.QLabel(self.topLayoutGroup_4)
        self.imageLabel_5.setText("")
        self.imageLabel_5.setPixmap(QtGui.QPixmap("resources/reavaultDark.png"))
        self.imageLabel_5.setScaledContents(True)
        self.imageLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel_5.setObjectName("imageLabel_5")
        self.topLayout_5.addWidget(self.imageLabel_5, 1, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_5.addItem(spacerItem30, 1, 2, 1, 1)
        self.appName_5 = QtWidgets.QLabel(self.topLayoutGroup_4)
        self.appName_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.appName_5.setAlignment(QtCore.Qt.AlignCenter)
        self.appName_5.setObjectName("appName_5")
        self.topLayout_5.addWidget(self.appName_5, 3, 1, 1, 1)
        self.versionName_5 = QtWidgets.QLabel(self.topLayoutGroup_4)
        self.versionName_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.versionName_5.setAlignment(QtCore.Qt.AlignCenter)
        self.versionName_5.setObjectName("versionName_5")
        self.topLayout_5.addWidget(self.versionName_5, 4, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout_5.addItem(spacerItem31, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.topLayoutGroup_4)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.topLayout_5.addWidget(self.label_5, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.topLayoutGroup_4)
        self.bottomLayoutGroup_4 = QtWidgets.QGroupBox(self.page4)
        self.bottomLayoutGroup_4.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.bottomLayoutGroup_4.setObjectName("bottomLayoutGroup_4")
        self.bottomLayout_5 = QtWidgets.QGridLayout(self.bottomLayoutGroup_4)
        self.bottomLayout_5.setContentsMargins(0, 0, 0, 0)
        self.bottomLayout_5.setSpacing(0)
        self.bottomLayout_5.setObjectName("bottomLayout_5")
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_5.addItem(spacerItem32, 6, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_5.addItem(spacerItem33, 7, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.bottomLayoutGroup_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.bottomLayout_5.addWidget(self.comboBox_4, 2, 1, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_5.addItem(spacerItem34, 8, 1, 1, 1)
        self.confLabel_5 = QtWidgets.QLabel(self.bottomLayoutGroup_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confLabel_5.sizePolicy().hasHeightForWidth())
        self.confLabel_5.setSizePolicy(sizePolicy)
        self.confLabel_5.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.confLabel_5.setObjectName("confLabel_5")
        self.bottomLayout_5.addWidget(self.confLabel_5, 3, 1, 1, 1)
        self.nextBtn2_4 = QtWidgets.QPushButton(self.bottomLayoutGroup_4)
        self.nextBtn2_4.setStyleSheet("QPushButton{\n"
"    margin: 10px 60px 0px;\n"
"    padding: 10px 0px 10px;\n"
"    background-color: #2861b6;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(47, 117, 214);\n"
"}")
        self.nextBtn2_4.setObjectName("nextBtn2_4")
        self.bottomLayout_5.addWidget(self.nextBtn2_4, 7, 1, 1, 1)
        self.passLabel_5 = QtWidgets.QLabel(self.bottomLayoutGroup_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passLabel_5.sizePolicy().hasHeightForWidth())
        self.passLabel_5.setSizePolicy(sizePolicy)
        self.passLabel_5.setStyleSheet("margin: 10px 0px 10px;\n"
"color: rgb(255, 255, 255);")
        self.passLabel_5.setObjectName("passLabel_5")
        self.bottomLayout_5.addWidget(self.passLabel_5, 1, 1, 1, 1)
        self.confField_5 = QtWidgets.QLineEdit(self.bottomLayoutGroup_4)
        self.confField_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.confField_5.setObjectName("confField_5")
        self.bottomLayout_5.addWidget(self.confField_5, 4, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bottomLayout_5.addItem(spacerItem35, 7, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_5.addItem(spacerItem36, 0, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.bottomLayout_5.addItem(spacerItem37, 5, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.bottomLayoutGroup_4)
        self.stackedWidget.addWidget(self.page4)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.nextBtn.clicked.connect(lambda: self.verify("Step1"))
        self.nextBtn2.clicked.connect(lambda: self.verify("Step2"))
        self.nextBtn2_2.clicked.connect(lambda: self.verify("Step3"))
        self.nextBtn2_4.clicked.connect(lambda: self.verify("Step4"))
        self.isVisible.toggled.connect(self.changeEcho)

    def changeEcho(self):
        if self.isVisible.isChecked() == True:
            self.passField.setEchoMode(QtWidgets.QLineEdit.Normal)
            self.confField.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.passField.setEchoMode(QtWidgets.QLineEdit.Password)
            self.confField.setEchoMode(QtWidgets.QLineEdit.Password)

    def verify(self, mode=None):
        if mode == "Step1":
            self.uname = self.userField.text()
            self.pwd = self.passField.text()
            self.conf = self.confField.text()
            if self.uname.isspace() == True or self.uname == '' or self.pwd.isspace() == True or self.pwd == '':
                self.errorMsg("Nah, Not Accepting Space or Blank Only Input")

            else:
                if self.pwd == self.conf:
                    self.res = {
                            'username' : self.uname,
                            'password' : self.pwd,
                            'ques' : {
                                    'a' : '',
                                    'b' : '',
                                    'c' : ''
                            },
                            'ans' : {
                                    'a' : '',
                                    'b' : '',
                                    'c' : ''
                            }
                    }
                    self.stackedWidget.setCurrentIndex(1)

                else:
                    self.errorMsg()

        elif mode == "Step2":
            ques = self.comboBox.currentText()
            ans = self.confField_2.text()
            if ans.isspace() or ans == '':
                self.errorMsg("Nah, Not Accepting Space or Blank Only Input")

            else:
                self.res['ques']['a'] = ques
                self.res['ans']['a'] = ans
                self.question.remove(ques)
                self.comboBox_2.clear()
                self.comboBox_2.addItems(self.question)
                self.stackedWidget.setCurrentIndex(2)

        elif mode == "Step3":
            ques = self.comboBox_2.currentText()
            ans = self.confField_3.text()
            if ans.isspace() or ans == '':
                self.errorMsg("Nah, Not Accepting Space or Blank Only Input")

            else:
                self.res['ques']['b'] = ques
                self.res['ans']['b'] = ans
                self.question.remove(ques)
                self.comboBox_4.clear()
                self.comboBox_4.addItems(self.question)
                self.stackedWidget.setCurrentIndex(3)

        elif mode == "Step4":
            ques = self.comboBox_4.currentText()
            ans = self.confField_5.text()
            if ans.isspace() or ans == '':
                self.errorMsg("Nah, Not Accepting Space or Blank Only Input")

            else:
                self.res['ques']['c'] = ques
                self.res['ans']['c'] = ans
                self.question.remove(ques)
                self.comboBox_4.clear()
                self.comboBox_4.addItems(self.question)
                self.reavault.createUser(self.res)
                self.Login.show()
                self.SignUp.close()

    def setter(self, SignUp, Login):
        self.SignUp = SignUp
        self.Login = Login

    def errorMsg(self, information="Your password not same"):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Critical)

        msg.setText(information)
        msg.setWindowTitle("Error")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.exec_()

    def setBridge(self, reavault):
        self.reavault = reavault

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Reavault - Sign Up"))
        self.appName.setText(_translate("Form", "Reavault"))
        self.versionName.setText(_translate("Form", "Version Beta 0.0.1"))
        self.label.setText(_translate("Form", "\"Password Manager No.1 se-UTM\""))
        self.confLabel.setText(_translate("Form", "Confirmation Password"))
        self.nextBtn.setText(_translate("Form", "Next"))
        self.isVisible.setText(_translate("Form", "make password visible"))
        self.userLabel.setText(_translate("Form", "Username"))
        self.passLabel.setText(_translate("Form", "Password"))
        self.appName_2.setText(_translate("Form", "Reavault"))
        self.versionName_2.setText(_translate("Form", "Version Beta 0.0.1"))
        self.label_2.setText(_translate("Form", "\"Password Manager No.1 se-UTM\""))
        self.question = ["Siapa nama ibumu?", "Dimana anda tinggal?", "Apa nama masa kecil anda?", "Warna favorit?", "Makanan kesukaan?"]
        self.comboBox.addItems(self.question)
        self.confLabel_2.setText(_translate("Form", "Answer"))
        self.nextBtn2.setText(_translate("Form", "Next"))
        self.passLabel_2.setText(_translate("Form", "Question 1 of 3"))
        self.appName_4.setText(_translate("Form", "Reavault"))
        self.versionName_4.setText(_translate("Form", "Version Beta 0.0.1"))
        self.label_4.setText(_translate("Form", "\"Password Manager No.1 se-UTM\""))
        self.comboBox_2.addItems(self.question)
        self.confLabel_3.setText(_translate("Form", "Answer"))
        self.nextBtn2_2.setText(_translate("Form", "Next"))
        self.passLabel_3.setText(_translate("Form", "Question 2 of 3"))
        self.appName_5.setText(_translate("Form", "Reavault"))
        self.versionName_5.setText(_translate("Form", "Version Beta 0.0.1"))
        self.label_5.setText(_translate("Form", "\"Password Manager No.1 se-UTM\""))
        self.comboBox_4.addItems(self.question)
        self.confLabel_5.setText(_translate("Form", "Answer"))
        self.nextBtn2_4.setText(_translate("Form", "Finish"))
        self.passLabel_5.setText(_translate("Form", "Question 3 of 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
